config/routes.rb
Rails.application.routes.draw do

  resources :checkouts

  resources :cart_items

  resources :carts
  resources :products

  get 'session/login'
  post 'session/create'
  delete 'session/logout'

  resources :users

  root 'products#index'

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id            :integer          not null, primary key
#  title         :string
#  description   :text
#  price         :decimal(10, 2)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  cart_items_id :integer
#

class Product < ActiveRecord::Base

  has_many :cart_items

  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :price

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin, only: [:edit, :update, :destroy]



  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show

    if current_user
      @cart = current_user.carts.last
      @cart_item = CartItem.new
    else
      @cart = nil
    end

  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>



<h1>These Are The Things You Can Buy</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= image_tag("#{product.id}.jpeg", size: '50x50') %></td>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'View Thing', product, class:'btn btn-sm btn-success' %></td>

        <% if current_user  %>
            <% if current_user.admin  %>
                <td><%= link_to 'Edit', edit_product_path(product) %></td>
                <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end  %>
        <% end  %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user  %>
    <% if current_user.admin  %>
        <%= link_to 'New Product', new_product_path %>
    <% end  %>
<% end  %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row">

  <div class="col-xs-4">
    <%= image_tag("#{@product.id}.jpg", size: '300x300') %>
  </div>

  <div class="col-xs-8">
      <h2><%= @product.title %></h2><br/>

    <p>
      <h4>Description</h4>
      <%= @product.description %><br/>
    </p>
    <br/>
    <p>
      <h4>Price: <small><%= @product.price %></small></h4>
    </p>

    <% if current_user %>

        <!--<%= render partial: 'cart_items/form', locals: {product: @product, cart: @cart} %>-->

        <%= button_to 'Add to Cart', cart_items_path(product_id: @product, cart_id: @cart), method: :post %>


    <% else %>
        <%= link_to 'Login or Sign Up to Purchase', session_login_path %>
    <% end %>
  </div>

</div>




<br/>
<br/>

<% if current_user  %>
    <% if current_user.admin  %>
        <%= link_to 'Edit', edit_product_path(@product) %> |
    <% end  %>
<% end  %>


<%= link_to 'Back', products_path %>